### ISSUE TITLE
Jenkins mirror will not work behind corporate proxy

### ISSUE THREAD

**Issue by samdunne** [sous-chefs/jenkins#398]
So in the case where using something such as artifactory to proxy the outside world, simply changing the jenkins mirror attribute is not enough to get the cookbook to work.

If a plugin is installed with dependencies the current functionality is to pull those dependencies from the URL's supplied within the metadata of the original plugin.

I could look at working around this in some way if it is a change you would be open to merging.

**Comment by tfitch** [comment]
Hello Sam,

I'd love to see increased support for running behind proxies because that's totally a thing.

I have one question to get my head around on here from when you say "pull those dependencies from URLs supplied within the metadata of the original plugin."

I haven't played with this much, but is this a proxy setting in Jenkins that can be set to make the correction, or a system wide proxy setting to correct the problem?

Regardless of the solution, if you can solve this problem inside the cookbook I'd love to see it and will help you get it merged.

**Comment by samdunne** [comment]
Hey,

That doesn't quite solve it. So in this scenario, jenkins has no direct route to the internet. Instead of using a proxy it is using artifactory to proxy certain things (such as it's RPM repository and it's plugin mirror).

I have a small work around for making the mirror change more reliable in this scenario. I'll clean it up and open a PR around this.

**Comment by jmaass** [comment]
I solved this in our environment by dropping a template proxy.xml in the $JENKINS_HOME directory that looks like this:

<?xml version='1.0' encoding='UTF-8'?>
<proxy>
  <name><%= @proxy_host %></name>
  <port><%= @proxy_port %></port>
  <noProxyHost><%= @no_proxy %></noProxyHost>
  <testUrl><%= @test_url %></testUrl>
</proxy>

The variables have to be set correctly, of course.

**Comment by jmaass** [comment]
Well, that's a way to handle feature requests, too. If you don't care about your customer's wishes...
