### ISSUE TITLE
Error executing action `create` on resource 'jenkins_job[name_redacted]' undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by dksAutodesk** [sous-chefs/jenkins#622]
### Cookbook version
depends 'jenkins', '~> 5.0.1'

### Chef-client version
chef-client -v
Chef: 12.14.89

### Platform Details
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-117-generic x86_64)
(via Vagrant running on Mac OS v. 10.12.5 - though I observed this error before upgrading to Sierra from El Capitan - my host OS is hopefully not involved in this issue)

### Scenario:
I'm running the cookbook to create a job on the desired target Jenkins Master.  

My metadata.rb contains:
`name 'jenkins-config'`
`version '0.1.0'`
`depends 'jenkins', '~> 5.0.1'`

After running the recipe `chef-client --local-mode -c ../config.rb -o 'recipe[jenkins-config::create-git-org-folder]'`, the following error is posted by chef-client

`NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Cookbook Trace:
    ---------------
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/jenkins/libraries/job.rb:308:in `correct_config?'
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/jenkins/libraries/job.rb:201:in `block in <class:JenkinsJob>'
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
    
    Resource Declaration:
    ---------------------
    # In /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/jenkins-config/recipes/create-git-org-folder.rb
    
     13:   jenkins_job job_name do
     14:     config config
     15:     action :create
     16:   end
     17: end
    
    Compiled Resource:
    ------------------
    # Declared in /vagrant/chef/cookbooks/local-mode-cache/cache/cookbooks/jenkins-config/recipes/create-git-org-folder.rb:13:in `block in from_file'
    
    jenkins_job("name_redacted") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :jenkins_job
      cookbook_name "jenkins-config"
      recipe_name "create-git-org-folder"
      config "/vagrant/chef/cookbooks/jenkins-config/files/name_redacted.xml"
    end
    
    Platform:
    ---------
    x86_64-linux`

### Steps to Reproduce:
From my recipe root dir (where my Berksfile is located):
`berks vendor ../vendored`
`chef-client --local-mode -c ../config.rb -o 'recipe[jenkins-config::create-git-org-folder]'`

Observe the error above but notice also the job object was in fact created on the target Jenkins Master.

### Expected Result:
The target jenkins job object is successfully created and and chef-client reports success (no error).

### Actual Result:
The jenkins job object is in fact created but the chef-client returns the error shown above.

**Comment by dksAutodesk** [comment]
Anyone watching?  I see a similar issue with #623 - though not exactly the same as this.  Anyone seen either of these?

**Comment by espoelstra** [comment]
This can happen if you have a plugin dependency that isn't properly satisfied. It seems a lot of people using this cookbook start to aggressively pin all plugins and their dependencies and use the `install_deps false` option. This doesn't play well when CloudBees creates a new plugin by pulling something out of the core of Jenkins.

What I've ended up doing is testing my plugins with the official Docker container to get all the deps pulled in during an upgrade, and I'm moving closer and closer to simply using Docker and an "immutable Jenkins" that I can spin up a new instance using the existing data/configs almost instantly instead of having Chef (slowly) try to manage the plugins and other components of the system and having to add code to "unmanage" plugins installed by people messing around that are rarely worth keeping for production. Having it in Docker also means they can spin it up and mess around on THEIR machine without junking up the important instances.
